apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/nextcloud-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pv-claim
  labels:
    app: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi